openapi: 3.0.0
info:
  title: Ticket Management API
  version: 1.0.0
  description: API for managing tickets
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/tickets:
    post:
      summary: Create a new ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the ticket
                description:
                  type: string
                  description: Description of the ticket
                contactInfo:
                  type: string
                  description: Contact information for the ticket
              required:
                - title
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier for the ticket
                  title:
                    type: string
                    description: Title of the ticket
                  description:
                    type: string
                    description: Description of the ticket
                  contactInfo:
                    type: string
                    description: Contact information for the ticket
        "500":
          description: Internal Server Error
    get:
      summary: Get all tickets
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Unique identifier for the ticket
                    title:
                      type: string
                      description: Title of the ticket
                    description:
                      type: string
                      description: Description of the ticket
                    contactInfo:
                      type: string
                      description: Contact information for the ticket
        "500":
          description: Internal Server Error
    servers:
      - url: /api/tickets
  /api/tickets/{id}:
    post:
      summary: Update a ticket
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the ticket to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Updated title of the ticket
                description:
                  type: string
                  description: Updated description of the ticket
                contactInfo:
                  type: string
                  description: Updated contact information for the ticket
              required:
                - title
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier for the ticket
                  title:
                    type: string
                    description: Updated title of the ticket
                  description:
                    type: string
                    description: Updated description of the ticket
                  contactInfo:
                    type: string
                    description: Updated contact information for the ticket
        "500":
          description: Internal Server Error
    servers:
      - url: /api/tickets/{id}
  /api/tickets/mock:
    get:
      summary: Mock data for tickets
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: Title of the ticket
                        description:
                          type: string
                          description: Description of the ticket
                        contactInfo:
                          type: string
                          description: Contact information for the ticket
        "500":
          description: Internal Server Error
    servers:
      - url: /api/tickets/mock
